plugins: stylelint-prettier
extends:
  - stylelint-config-standard
  - stylelint-config-recess-order
  - stylelint-config-prettie
overrides: 
  - files:
    - 'src/**/*.{ts,tsx}'
    customSyntax: '@stylelint/postcss-css-in-js'
rules:
  - string-quotes:
    - 'single'